---
- name: Packages
  hosts: localhost
  become: yes
  tasks:
     - name: Install Packages
       yum: 
          name: "{{ item }}" 
          state: present
          with_items:
              - nginx
              - mysql
              - php
