---
- name: Prints target node
  hosts: localhost
  gather_facts: yes
  tasks:
   - name:
     debug:
       msg: 
       - "Hostname is {{ ansible_hostname}}"
       - "OS family is {{ ansible_os_family}}"
       - "OS version is {{ ansible_distribution_version}}"
